version: '3.1'
services:
    coredns:
        build: .
        container_name: coredns
        restart: always # other option: always - if you want persistent through host reboots
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - '/data/coredns/config:/etc/coredns'
